# Generated by Django 4.0.4 on 2022-05-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_participants_collegename'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='points',
            field=models.IntegerField(default=-1),
        ),
    ]
