# Generated by Django 4.0.4 on 2022-05-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_participants_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='endtime',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='starttime',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
    ]
