# Generated by Django 4.0.4 on 2022-05-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_participants_endtime_participants_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='totaltime',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
    ]
