# Generated by Django 4.0.4 on 2022-05-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_participants_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='teamname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
