# Generated by Django 4.0.4 on 2022-05-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_alter_participants_teamname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='points',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='totaltime',
        ),
        migrations.AddField(
            model_name='participants',
            name='level1',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='level2',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='level3',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='level4',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='level5',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='points1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='participants',
            name='points2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='participants',
            name='totaltime1',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
        migrations.AddField(
            model_name='participants',
            name='totaltime2',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
    ]
