# Generated by Django 4.0.4 on 2022-05-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_remove_participants_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='starttime',
            field=models.CharField(default='0:0:0', max_length=10),
        ),
    ]
