# Generated by Django 4.0.4 on 2022-05-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_participants_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='collegename',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='level3',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='level4',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='level5',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='points1',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='points2',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='teamname',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='totaltime1',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='totaltime2',
        ),
    ]
