# Generated by Django 4.0.4 on 2022-05-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_participants_collegename_participants_level1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='teamname',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
