# Generated by Django 4.0.4 on 2022-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0015_finalers_remove_participants_level4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='phoneno',
            field=models.CharField(default='NULL', max_length=13),
        ),
    ]
