# Generated by Django 4.0.4 on 2022-05-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0016_participants_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalers',
            name='phoneno',
            field=models.CharField(default='NULL', max_length=13),
        ),
        migrations.AddField(
            model_name='participants',
            name='set',
            field=models.CharField(default='NULL', max_length=5),
        ),
    ]
